package org.xen.jna.xenstat;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 52</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xenstat_tmem extends Structure {
	public long curr_eph_pages;
	public long succ_eph_gets;
	public long succ_pers_puts;
	public long succ_pers_gets;
	public xenstat_tmem() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("curr_eph_pages", "succ_eph_gets", "succ_pers_puts", "succ_pers_gets");
	}
	public xenstat_tmem(long curr_eph_pages, long succ_eph_gets, long succ_pers_puts, long succ_pers_gets) {
		super();
		this.curr_eph_pages = curr_eph_pages;
		this.succ_eph_gets = succ_eph_gets;
		this.succ_pers_puts = succ_pers_puts;
		this.succ_pers_gets = succ_pers_gets;
	}
	public xenstat_tmem(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xenstat_tmem implements Structure.ByReference {
		
	};
	public static class ByValue extends xenstat_tmem implements Structure.ByValue {
		
	};
}
