package org.xen.stat;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 92</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xenstat_vcpu extends Structure {
	public int online;
	public long ns;
	public xenstat_vcpu() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("online", "ns");
	}
	public xenstat_vcpu(int online, long ns) {
		super();
		this.online = online;
		this.ns = ns;
	}
	public xenstat_vcpu(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xenstat_vcpu implements Structure.ByReference {
		
	};
	public static class ByValue extends xenstat_vcpu implements Structure.ByValue {
		
	};
}

