package org.xen.stat;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 111</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xenstat_vbd extends Structure {
	public int back_type;
	public int dev;
	public long oo_reqs;
	public long rd_reqs;
	public long wr_reqs;
	public long rd_sects;
	public long wr_sects;
	public xenstat_vbd() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("back_type", "dev", "oo_reqs", "rd_reqs", "wr_reqs", "rd_sects", "wr_sects");
	}
	public xenstat_vbd(int back_type, int dev, long oo_reqs, long rd_reqs, long wr_reqs, long rd_sects, long wr_sects) {
		super();
		this.back_type = back_type;
		this.dev = dev;
		this.oo_reqs = oo_reqs;
		this.rd_reqs = rd_reqs;
		this.wr_reqs = wr_reqs;
		this.rd_sects = rd_sects;
		this.wr_sects = wr_sects;
	}
	public xenstat_vbd(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xenstat_vbd implements Structure.ByReference {
		
	};
	public static class ByValue extends xenstat_vbd implements Structure.ByValue {
		
	};
}

